name: Run Cypress Tests

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start # Replace with your start command if different
          browser: chrome # Or edge, firefox, electron
          config: |
            {
              "reporter": "cypress-multi-reporters",
              "reporterOptions": {
                "reporterEnabled": "mochawesome, cypress-mochawesome-reporter, cypress-junit-reporter, mocha-junit-reporter",
                "mochaJunitReporterReporterOptions": {
                  "mochaFile": "cypress/reports/junit/results-[hash].xml",
                  "toConsole": false
                },
                "cypressMochawesomeReporterReporterOptions": {
                  "charts": true,
                  "reportPageTitle": "Cypress Mochawesome Report",
                  "embeddedScreenshots": true,
                  "inlineAssets": true,
                  "saveAllAttempts": false,
                  "overwrite": true
                },
                "mochaFile": "cypress/reports/junit/results-[hash].xml"
              },
              "cucumberPreprocessor": {
                "nonGlobalStepDefinitions": true
              }
            }
          cucumber: |
            {
              "format": "json:cypress/cucumber-json/cucumber.json",
              "html": {
                "enabled": true,
                "output": "cypress/reports/cucumber-report.html"
              }
            }
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-html-report
          path: cypress/reports/cucumber-report.html
      - name: Upload Cypress Mochawesome Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-mochawesome-report
          path: cypress/reports/mochawesome.html
      - name: Upload Junit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-junit-report
          path: cypress/reports/junit/